#pragma once

// From glfw3.h

/*----------Keyboard----------*/

/* The unknown key */
#define GNT_KEY_UNKNOWN -1

/* Printable keys */
#define GNT_KEY_SPACE 32
#define GNT_KEY_APOSTROPHE 39 /* ' */
#define GNT_KEY_COMMA 44      /* , */
#define GNT_KEY_MINUS 45      /* - */
#define GNT_KEY_PERIOD 46     /* . */
#define GNT_KEY_SLASH 47      /* / */
#define GNT_KEY_0 48
#define GNT_KEY_1 49
#define GNT_KEY_2 50
#define GNT_KEY_3 51
#define GNT_KEY_4 52
#define GNT_KEY_5 53
#define GNT_KEY_6 54
#define GNT_KEY_7 55
#define GNT_KEY_8 56
#define GNT_KEY_9 57
#define GNT_KEY_SEMICOLON 59 /* ; */
#define GNT_KEY_EQUAL 61     /* = */
#define GNT_KEY_A 65
#define GNT_KEY_B 66
#define GNT_KEY_C 67
#define GNT_KEY_D 68
#define GNT_KEY_E 69
#define GNT_KEY_F 70
#define GNT_KEY_G 71
#define GNT_KEY_H 72
#define GNT_KEY_I 73
#define GNT_KEY_J 74
#define GNT_KEY_K 75
#define GNT_KEY_L 76
#define GNT_KEY_M 77
#define GNT_KEY_N 78
#define GNT_KEY_O 79
#define GNT_KEY_P 80
#define GNT_KEY_Q 81
#define GNT_KEY_R 82
#define GNT_KEY_S 83
#define GNT_KEY_T 84
#define GNT_KEY_U 85
#define GNT_KEY_V 86
#define GNT_KEY_W 87
#define GNT_KEY_X 88
#define GNT_KEY_Y 89
#define GNT_KEY_Z 90
#define GNT_KEY_LEFT_BRACKET 91  /* [ */
#define GNT_KEY_BACKSLASH 92     /* \ */
#define GNT_KEY_RIGHT_BRACKET 93 /* ] */
#define GNT_KEY_GRAVE_ACCENT 96  /* ` */
#define GNT_KEY_WORLD_1 161      /* non-US #1 */
#define GNT_KEY_WORLD_2 162      /* non-US #2 */

/* Function keys */
#define GNT_KEY_ESCAPE 256
#define GNT_KEY_ENTER 257
#define GNT_KEY_TAB 258
#define GNT_KEY_BACKSPACE 259
#define GNT_KEY_INSERT 260
#define GNT_KEY_DELETE 261
#define GNT_KEY_RIGHT 262
#define GNT_KEY_LEFT 263
#define GNT_KEY_DOWN 264
#define GNT_KEY_UP 265
#define GNT_KEY_PAGE_UP 266
#define GNT_KEY_PAGE_DOWN 267
#define GNT_KEY_HOME 268
#define GNT_KEY_END 269
#define GNT_KEY_CAPS_LOCK 280
#define GNT_KEY_SCROLL_LOCK 281
#define GNT_KEY_NUM_LOCK 282
#define GNT_KEY_PRINT_SCREEN 283
#define GNT_KEY_PAUSE 284
#define GNT_KEY_F1 290
#define GNT_KEY_F2 291
#define GNT_KEY_F3 292
#define GNT_KEY_F4 293
#define GNT_KEY_F5 294
#define GNT_KEY_F6 295
#define GNT_KEY_F7 296
#define GNT_KEY_F8 297
#define GNT_KEY_F9 298
#define GNT_KEY_F10 299
#define GNT_KEY_F11 300
#define GNT_KEY_F12 301
#define GNT_KEY_F13 302
#define GNT_KEY_F14 303
#define GNT_KEY_F15 304
#define GNT_KEY_F16 305
#define GNT_KEY_F17 306
#define GNT_KEY_F18 307
#define GNT_KEY_F19 308
#define GNT_KEY_F20 309
#define GNT_KEY_F21 310
#define GNT_KEY_F22 311
#define GNT_KEY_F23 312
#define GNT_KEY_F24 313
#define GNT_KEY_F25 314
#define GNT_KEY_KP_0 320
#define GNT_KEY_KP_1 321
#define GNT_KEY_KP_2 322
#define GNT_KEY_KP_3 323
#define GNT_KEY_KP_4 324
#define GNT_KEY_KP_5 325
#define GNT_KEY_KP_6 326
#define GNT_KEY_KP_7 327
#define GNT_KEY_KP_8 328
#define GNT_KEY_KP_9 329
#define GNT_KEY_KP_DECIMAL 330
#define GNT_KEY_KP_DIVIDE 331
#define GNT_KEY_KP_MULTIPLY 332
#define GNT_KEY_KP_SUBTRACT 333
#define GNT_KEY_KP_ADD 334
#define GNT_KEY_KP_ENTER 335
#define GNT_KEY_KP_EQUAL 336
#define GNT_KEY_LEFT_SHIFT 340
#define GNT_KEY_LEFT_CONTROL 341
#define GNT_KEY_LEFT_ALT 342
#define GNT_KEY_LEFT_SUPER 343
#define GNT_KEY_RIGHT_SHIFT 344
#define GNT_KEY_RIGHT_CONTROL 345
#define GNT_KEY_RIGHT_ALT 346
#define GNT_KEY_RIGHT_SUPER 347
#define GNT_KEY_MENU 348

/*----------Mouse----------*/

#define GNT_MOUSE_BUTTON_1 0
#define GNT_MOUSE_BUTTON_2 1
#define GNT_MOUSE_BUTTON_3 2
#define GNT_MOUSE_BUTTON_4 3
#define GNT_MOUSE_BUTTON_5 4
#define GNT_MOUSE_BUTTON_6 5
#define GNT_MOUSE_BUTTON_7 6
#define GNT_MOUSE_BUTTON_8 7
#define GNT_MOUSE_BUTTON_LAST GNT_MOUSE_BUTTON_8
#define GNT_MOUSE_BUTTON_LEFT GNT_MOUSE_BUTTON_1
#define GNT_MOUSE_BUTTON_RIGHT GNT_MOUSE_BUTTON_2
#define GNT_MOUSE_BUTTON_MIDDLE GNT_MOUSE_BUTTON_3

/*----------Joystick----------*/

#define GNT_JOYSTICK_1 0
#define GNT_JOYSTICK_2 1
#define GNT_JOYSTICK_3 2
#define GNT_JOYSTICK_4 3
#define GNT_JOYSTICK_5 4
#define GNT_JOYSTICK_6 5
#define GNT_JOYSTICK_7 6
#define GNT_JOYSTICK_8 7
#define GNT_JOYSTICK_9 8
#define GNT_JOYSTICK_10 9
#define GNT_JOYSTICK_11 10
#define GNT_JOYSTICK_12 11
#define GNT_JOYSTICK_13 12
#define GNT_JOYSTICK_14 13
#define GNT_JOYSTICK_15 14
#define GNT_JOYSTICK_16 15
#define GNT_JOYSTICK_LAST GNT_JOYSTICK_16

/*----------Gamepad----------*/

#define GNT_GAMEPAD_BUTTON_A 0
#define GNT_GAMEPAD_BUTTON_B 1
#define GNT_GAMEPAD_BUTTON_X 2
#define GNT_GAMEPAD_BUTTON_Y 3
#define GNT_GAMEPAD_BUTTON_LEFT_BUMPER 4
#define GNT_GAMEPAD_BUTTON_RIGHT_BUMPER 5
#define GNT_GAMEPAD_BUTTON_BACK 6
#define GNT_GAMEPAD_BUTTON_START 7
#define GNT_GAMEPAD_BUTTON_GUIDE 8
#define GNT_GAMEPAD_BUTTON_LEFT_THUMB 9
#define GNT_GAMEPAD_BUTTON_RIGHT_THUMB 10
#define GNT_GAMEPAD_BUTTON_DPAD_UP 11
#define GNT_GAMEPAD_BUTTON_DPAD_RIGHT 12
#define GNT_GAMEPAD_BUTTON_DPAD_DOWN 13
#define GNT_GAMEPAD_BUTTON_DPAD_LEFT 14
#define GNT_GAMEPAD_BUTTON_LAST GNT_GAMEPAD_BUTTON_DPAD_LEFT

#define GNT_GAMEPAD_BUTTON_CROSS GNT_GAMEPAD_BUTTON_A
#define GNT_GAMEPAD_BUTTON_CIRCLE GNT_GAMEPAD_BUTTON_B
#define GNT_GAMEPAD_BUTTON_SQUARE GNT_GAMEPAD_BUTTON_X
#define GNT_GAMEPAD_BUTTON_TRIANGLE GNT_GAMEPAD_BUTTON_Y

#define GNT_GAMEPAD_AXIS_LEFT_X 0
#define GNT_GAMEPAD_AXIS_LEFT_Y 1
#define GNT_GAMEPAD_AXIS_RIGHT_X 2
#define GNT_GAMEPAD_AXIS_RIGHT_Y 3
#define GNT_GAMEPAD_AXIS_LEFT_TRIGGER 4
#define GNT_GAMEPAD_AXIS_RIGHT_TRIGGER 5
#define GNT_GAMEPAD_AXIS_LAST GNT_GAMEPAD_AXIS_RIGHT_TRIGGER